services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $applicationServiceUsersEndpoint: '%env(resolve:APPLICATION_SERVICE_USERS_ENDPOINT)%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\Listener\JsonExceptionResponseTransformerListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 100 }
