framework:
  messenger:
    serializer:
      default_serializer: messenger.transport.symfony_serializer
      symfony_serializer:
        format: json
        context: { }

    transports:
      async_register_application:
        dsn: '%env(string:MESSENGER_TRANSPORT_DSN)%'
        options:
          vhost: '%env(string:MESSENGER_VHOST)%'
          exchange:
            name: '%env(string:MESSENGER_EXCHANGE)%'
            type: direct
          queues:
            register_application_queue:
              binding_keys: [ register_application_queue ]

    routing:
      'App\Messenger\Message\UserRegisteredMessage': async_register_application
